services:
  web:
    build: .
    image: life-span-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    restart: always
    develop:
      watch:
        - path: ./src
          action: rebuild
          target: /usr/share/nginx/html
